package vista;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CircuitoSerieBtn = new javax.swing.JButton();
        CircuitoParaleloBtn = new javax.swing.JButton();
        CircuitoMixtoBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CircuitoSerieBtn.setText("Circuito en serie");
        CircuitoSerieBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CircuitoSerieBtnMouseClicked(evt);
            }
        });
        CircuitoSerieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircuitoSerieBtnActionPerformed(evt);
            }
        });

        CircuitoParaleloBtn.setText("Circuito en paralelo");
        CircuitoParaleloBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CircuitoParaleloBtnMouseClicked(evt);
            }
        });
        CircuitoParaleloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircuitoParaleloBtnActionPerformed(evt);
            }
        });

        CircuitoMixtoBtn1.setText("Circuito mixto");
        CircuitoMixtoBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CircuitoMixtoBtn1MouseClicked(evt);
            }
        });
        CircuitoMixtoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircuitoMixtoBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CircuitoMixtoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CircuitoParaleloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CircuitoSerieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(CircuitoSerieBtn)
                .addGap(84, 84, 84)
                .addComponent(CircuitoParaleloBtn)
                .addGap(62, 62, 62)
                .addComponent(CircuitoMixtoBtn1)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CircuitoParaleloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircuitoParaleloBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CircuitoParaleloBtnActionPerformed

    private void CircuitoMixtoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircuitoMixtoBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CircuitoMixtoBtn1ActionPerformed

    private void CircuitoSerieBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CircuitoSerieBtnMouseClicked
        // TODO add your handling code here:
        Serie serie = new Serie();
        serie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CircuitoSerieBtnMouseClicked

    private void CircuitoParaleloBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CircuitoParaleloBtnMouseClicked
        // TODO add your handling code here:
        Paralelo paralelo = new Paralelo();
        paralelo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CircuitoParaleloBtnMouseClicked

    private void CircuitoMixtoBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CircuitoMixtoBtn1MouseClicked
        // TODO add your handling code here:
        Mixto mixto = new Mixto();
        mixto.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CircuitoMixtoBtn1MouseClicked

    private void CircuitoSerieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircuitoSerieBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CircuitoSerieBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CircuitoMixtoBtn1;
    private javax.swing.JButton CircuitoParaleloBtn;
    private javax.swing.JButton CircuitoSerieBtn;
    // End of variables declaration//GEN-END:variables
}
