package vista;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Mixto extends javax.swing.JFrame {


    FondoPanel fondo = new FondoPanel();
    
        private void MensajeSoloNumeros(java.awt.event.KeyEvent  e){
        char validar=e.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            e.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }

    public Mixto() {
       // this.setContentPane(fondo);
        initComponents();
        TextPrompt placeholder1 = new TextPrompt("Ohmios", z1r);
        TextPrompt placeholder2 = new TextPrompt("Ohmios", z2r);
        TextPrompt placeholder3 = new TextPrompt("Ohmios", z3r);
        TextPrompt placeholder4 = new TextPrompt("Faradios", z1c);
        TextPrompt placeholder5 = new TextPrompt("Faradios", z2c);
        TextPrompt placeholder6 = new TextPrompt("Faradios", z3c);
        TextPrompt placeholder7 = new TextPrompt("Henrriors", z1l);
        TextPrompt placeholder8 = new TextPrompt("Henrriors", z2l);
        TextPrompt placeholder9 = new TextPrompt("Henrriors", z3l);
        TextPrompt placeholder10 = new TextPrompt("Voltaje con angulo", voltaje);
        TextPrompt placeholder11 = new TextPrompt("Frecuencia", frecuencia);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ohms = new javax.swing.ButtonGroup();
        Hrzs = new javax.swing.ButtonGroup();
        Fs = new javax.swing.ButtonGroup();
        Hs = new javax.swing.ButtonGroup();
        ImagenPanel = new FondoPanel();
        KHrz = new javax.swing.JRadioButton();
        Hrz = new javax.swing.JRadioButton();
        Omh = new javax.swing.JRadioButton();
        KOhm = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        uF = new javax.swing.JRadioButton();
        H = new javax.swing.JRadioButton();
        uH = new javax.swing.JRadioButton();
        voltaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nH = new javax.swing.JRadioButton();
        nF = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        z2r = new javax.swing.JTextField();
        z2c = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        z2l = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        frecuencia = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CalcularBtn = new javax.swing.JButton();
        VolverBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        z1r = new javax.swing.JTextField();
        z1c = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        z1l = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        z3r = new javax.swing.JTextField();
        z3c = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        z3l = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(2147483647, 2147483647, 2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ImagenPanelLayout = new javax.swing.GroupLayout(ImagenPanel);
        ImagenPanel.setLayout(ImagenPanelLayout);
        ImagenPanelLayout.setHorizontalGroup(
            ImagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        ImagenPanelLayout.setVerticalGroup(
            ImagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(ImagenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 410, 270));

        Hrzs.add(KHrz);
        KHrz.setText("KHrz");
        getContentPane().add(KHrz, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, -1, -1));

        Hrzs.add(Hrz);
        Hrz.setText("Hrz");
        Hrz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HrzActionPerformed(evt);
            }
        });
        getContentPane().add(Hrz, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, -1, -1));

        Ohms.add(Omh);
        Omh.setText("Ohm");
        getContentPane().add(Omh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, -1));

        Ohms.add(KOhm);
        KOhm.setText("KOhm");
        getContentPane().add(KOhm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, -1, -1));

        Fs.add(F);
        F.setText("F");
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, -1, -1));

        Fs.add(uF);
        uF.setText("uF");
        getContentPane().add(uF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 640, -1, -1));

        Hs.add(H);
        H.setText("H");
        getContentPane().add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, -1, -1));

        Hs.add(uH);
        uH.setText("uH");
        getContentPane().add(uH, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, -1, -1));
        getContentPane().add(voltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 140, -1));

        jLabel1.setText("Hercios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, -1));

        jLabel2.setText("Ohmios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, -1, -1));

        jLabel3.setText("Faradios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, -1, -1));

        jLabel4.setText("Henrriors");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        Hs.add(nH);
        nH.setText("nH");
        getContentPane().add(nH, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, -1, -1));

        Fs.add(nF);
        nF.setText("nF");
        nF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFActionPerformed(evt);
            }
        });
        getContentPane().add(nF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 670, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Valor de R en Ohm");

        z2r.setName("z2r"); // NOI18N
        z2r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2rActionPerformed(evt);
            }
        });
        z2r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z2rKeyTyped(evt);
            }
        });

        z2c.setName("r"); // NOI18N
        z2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2cActionPerformed(evt);
            }
        });
        z2c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z2cKeyTyped(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Valor de L en H");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Valor de C en F");

        z2l.setName("r"); // NOI18N
        z2l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2lActionPerformed(evt);
            }
        });
        z2l.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z2lKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(z2l, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z2c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z2r, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(z2r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(z2l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(z2c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 220, 170));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Z1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 220, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Z3");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 220, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Z2");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 70, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Voltaje con angulo");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 120, -1));

        frecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecuenciaActionPerformed(evt);
            }
        });
        getContentPane().add(frecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 110, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Frecuencia en Hz");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, -1));

        CalcularBtn.setText("Calcular");
        CalcularBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcularBtnMouseClicked(evt);
            }
        });
        CalcularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularBtnActionPerformed(evt);
            }
        });
        CalcularBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CalcularBtnKeyPressed(evt);
            }
        });
        getContentPane().add(CalcularBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 130, 60));

        VolverBtn.setText("Volver");
        VolverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverBtnMouseClicked(evt);
            }
        });
        VolverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(VolverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 640, 130, 40));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Valor de R en Ohm");

        z1r.setName("r"); // NOI18N
        z1r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1rActionPerformed(evt);
            }
        });
        z1r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z1rKeyTyped(evt);
            }
        });

        z1c.setName("r"); // NOI18N
        z1c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1cActionPerformed(evt);
            }
        });
        z1c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z1cKeyTyped(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Valor de L en H");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Valor de C en F");

        z1l.setName("r"); // NOI18N
        z1l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z1lActionPerformed(evt);
            }
        });
        z1l.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z1lKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(z1c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z1l, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z1r, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(z1r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(11, 11, 11)
                .addComponent(z1l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(z1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 220, 210));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Valor de R en Ohm");

        z3r.setName("r"); // NOI18N
        z3r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z3rActionPerformed(evt);
            }
        });
        z3r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z3rKeyTyped(evt);
            }
        });

        z3c.setName("r"); // NOI18N
        z3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z3cActionPerformed(evt);
            }
        });
        z3c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z3cKeyTyped(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Valor de L en H");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Valor de C en F");

        z3l.setName("r"); // NOI18N
        z3l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z3lActionPerformed(evt);
            }
        });
        z3l.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                z3lKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(z3l, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z3c, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z3r, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(z3r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(11, 11, 11)
                .addComponent(z3l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(z3c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nFActionPerformed

    private void frecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecuenciaActionPerformed

    private void VolverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverBtnActionPerformed

    private void VolverBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBtnMouseClicked
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverBtnMouseClicked

    private void CalcularBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularBtnMouseClicked
        // TODO add your handling code here:
     //   ResultadosSerie rSerie= new ResultadosSerie();
     //   rSerie.setVisible(true);
     //   this.setVisible(false);
    }//GEN-LAST:event_CalcularBtnMouseClicked

    private void z2rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2rActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_z2rActionPerformed

    private void z2rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z2rKeyTyped
        MensajeSoloNumeros(evt);
        
    }//GEN-LAST:event_z2rKeyTyped

    private void CalcularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularBtnActionPerformed
        
        //Recoleccion de datos
        double Sfrecuencia = Float.parseFloat(frecuencia.getText());
        double Svoltaje = Float.parseFloat(voltaje.getText());
        double Z1r = Float.parseFloat(z1r.getText());
        double Z2r = Float.parseFloat(z2r.getText());
        double Z3r = Float.parseFloat(z3r.getText());
        double Z1c = Float.parseFloat(z1c.getText());
        double Z2c = Float.parseFloat(z2c.getText());
        double Z3c = Float.parseFloat(z3c.getText());
        double Z1l = Float.parseFloat(z1l.getText());
        double Z2l = Float.parseFloat(z2l.getText());
        double Z3l = Float.parseFloat(z3l.getText());
        

        // Converison de Frecuencia
        if(!Hrz.isSelected()){
            Sfrecuencia = Sfrecuencia*1000;
        }
        
        // Converison de Ohm (r)
        if(!Omh.isSelected()){
         Z1r = Z1r*1000;
         Z2r = Z2r*1000;
         Z3r = Z3r*1000;
        }
        
        //Grupo de Faradios (c)

        if(F.isSelected()){
           //no pasa nada :D
        }else if(uF.isSelected()){
            
         Z1c = Z1c/1000000;
         Z2c = Z2c/1000000;
         Z3c = Z3c/1000000;
         
        }else if(nF.isSelected()){
            
         Z1c = Z1c/1000000000;
         Z2c = Z2c/1000000000;
         Z3c = Z3c/1000000000;
        }
        
        //Grupo de Henrriors (l)
        if(H.isSelected()){
         //no pasa nada :D
        }else if(uH.isSelected()){
            
         Z1l = Z1l/1000000;
         Z2l = Z2l/1000000;
         Z3l = Z3l/1000000;
         
        }else if(nH.isSelected()){
            
         Z1l = Z1l/1000000000;
         Z2l = Z2l/1000000000;
         Z3l = Z3l/1000000000;
        }

           
           double w = Sfrecuencia*2*Math.PI;
           
           //Para Z1
           double Xc1 = 1/w*Z1c;
           double Xl1 = w*Z1l;
           double Z1 = Math.sqrt(Math.pow(Z1r, 2) + Math.pow((Xl1-Xc1), 2));
           
           //Para Z2
           double Xc2 = 1/w*Z2c;
           double Xl2 = w*Z2l;
           double Z2 = Math.sqrt(Math.pow(Z2r, 2) + Math.pow((Xl2-Xc2), 2));
           
           //Para Z3
           double Xc3 = 1/w*Z3c;
           double Xl3 = w*Z3l;
           double Z3 = Math.sqrt(Math.pow(Z3r, 2) + Math.pow((Xl3-Xc3), 3));

           //Calculo ZT
           
           double Z4 = (Z2+Z3);
           double Zt = ((Z4*Z1)/(Z4+Z1));
           
            //Calculo IT
           
           double It = Svoltaje/Zt;
           
           //Calculo IZ
           
           double Iz1 = Svoltaje/Z1;
           
           //Calculo VT
           
           double Vt = Zt*It;
           
           // Transformacion de double a text
           
           String tex_z1 = Double.toString(Z1);
           String tex_z2 = Double.toString(Z2);
           String tex_z3 = Double.toString(Z3);
           
           String tex_it = Double.toString(It);
           String tex_w = Double.toString(w);
           String tex_Iz1 = Double.toString(Iz1);
           String tex_vt = Double.toString(Vt);
           
          ResultadosMixto  a = new ResultadosMixto();
          a.setVisible(true);
          ResultadosMixto.rz1.setText(tex_z1);
          ResultadosMixto.rz2.setText(tex_z2);
          ResultadosMixto.rz3.setText(tex_z3);
          ResultadosMixto.rit.setText(tex_it);
          ResultadosMixto.rat.setText(tex_w);
          ResultadosMixto.rvz1.setText(tex_vt);
          ResultadosMixto.Iz1.setText(tex_Iz1);

          
          
    }//GEN-LAST:event_CalcularBtnActionPerformed

    private void HrzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HrzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HrzActionPerformed

    private void CalcularBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CalcularBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularBtnKeyPressed

    private void z2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2cActionPerformed

    private void z2cKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z2cKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z2cKeyTyped

    private void z2lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2lActionPerformed

    private void z2lKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z2lKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z2lKeyTyped

    private void z3rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z3rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z3rActionPerformed

    private void z3rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z3rKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z3rKeyTyped

    private void z3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z3cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z3cActionPerformed

    private void z3cKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z3cKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z3cKeyTyped

    private void z3lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z3lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z3lActionPerformed

    private void z3lKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z3lKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z3lKeyTyped

    private void z1rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1rActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1rActionPerformed

    private void z1rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z1rKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z1rKeyTyped

    private void z1cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1cActionPerformed

    private void z1cKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z1cKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z1cKeyTyped

    private void z1lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z1lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z1lActionPerformed

    private void z1lKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_z1lKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_z1lKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mixto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mixto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mixto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mixto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mixto().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularBtn;
    private javax.swing.JRadioButton F;
    private javax.swing.ButtonGroup Fs;
    private javax.swing.JRadioButton H;
    private javax.swing.JRadioButton Hrz;
    private javax.swing.ButtonGroup Hrzs;
    private javax.swing.ButtonGroup Hs;
    private javax.swing.JPanel ImagenPanel;
    private javax.swing.JRadioButton KHrz;
    private javax.swing.JRadioButton KOhm;
    private javax.swing.ButtonGroup Ohms;
    private javax.swing.JRadioButton Omh;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JTextField frecuencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton nF;
    private javax.swing.JRadioButton nH;
    private javax.swing.JRadioButton uF;
    private javax.swing.JRadioButton uH;
    private javax.swing.JTextField voltaje;
    private javax.swing.JTextField z1c;
    private javax.swing.JTextField z1l;
    private javax.swing.JTextField z1r;
    private javax.swing.JTextField z2c;
    private javax.swing.JTextField z2l;
    private javax.swing.JTextField z2r;
    private javax.swing.JTextField z3c;
    private javax.swing.JTextField z3l;
    private javax.swing.JTextField z3r;
    // End of variables declaration//GEN-END:variables
    public class FondoPanel extends JPanel {
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/Circuito en Mixto.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
}
